services:
  postgres:
    build: .
    container_name: lab1
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
